# Header
menu:
  主页: /
  所有文章: /archives 
  关于: http://www.libcz.com/about.html
  #TAGS: /tags/

# SubNav
subnav:
  jianshu_ios: "http://www.jianshu.com/users/b8b64af5b6f9/timeline"
  github: "http://github.com/cz-it"
  jianshu_golang: "http://www.jianshu.com/users/86f2f6a5968e/timeline"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /blog/atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: http://images.libcz.com:8000/images/favicon.png

#你的头像url
avatar: http://images.libcz.com:8000/images/white_bg_logo.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
